package includeautogenerated

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestIncludeAutoGenerated(t *testing.T) {
	m := NewMockFoo(t)
	m.EXPECT().Bar().Return("foo")
	assert.Equal(t, "foo", m.Bar())
}
